name: Run Image Request

on: 
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  run-country:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        location_nr: [
          0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,
          21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,
          39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,
          57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,
          75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: playwright install --with-deps

      - name: Run script for index ${{ matrix.location_nr }}
        run: |
          python image_request.py --location "${{ matrix.location_nr }}"

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ matrix.location_nr }}
          path: |
            dataset/
            errors/
            challenge_urls/

          if-no-files-found: ignore


  commit-and-push:
    runs-on: ubuntu-latest
    needs: run-country

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: false
          fetch-depth: 0

      - name: Download all artifacts 
        uses: actions/download-artifact@v4 
        with: 
          path: artifacts/

      - name: Move downloaded files into repo 
        run: | 
          cp -r artifacts/*/* dataset/ || true
          cp -r artifacts/*/* errors/ || true
          cp -r artifacts/*/* challenge_urls/ || true

      - name: Commit and push all changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add -A

          if ! git diff --cached --quiet; then
            git commit -m "Update dataset and logs (all countries)"
            git push origin main
          else
            echo "Keine Ã„nderungen, kein Commit."
          fi
